name: Update Playlist Every 15 Min
on:
  schedule:
    - cron: '*/15 * * * *' # รันทุก 15 นาที
  workflow_dispatch: # กดรันเองได้

jobs:
  update-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run Script
        run: python main.py
      # ... ส่วนบนของโค้ด YAML ...
     - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add luxdo_playlist.w3u # ชี้ไปที่ไฟล์ใน Root Directory
          git commit -m "Auto update: $(date)" || exit 0
          git push


